codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        base: auto
    patch:
      default:
        target: 70%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "node_modules/**/*"
  - "test/**/*"
  - "scripts/**/*"
  - "*.config.js"
  - "*.config.ts"

flags:
  unittests:
    paths:
      - contracts/
    carryforward: true
